---
title: "Label Switching"
author: "Xinnuo Chen"
date: "2025-04-02"
output: html_document
---

# K desicion's function
```{r}
set.seed(my.seed)
cp.values <- c(0.0001, 0.001, 0.01, 0.03, 0.05, 0.1)
minbucket.values <- c(1, 3, 5, 10, 20, 30, 60, 120)

synt.data <- synt.data.generation(
  real.data = real.data.1, 
  cp.values = cp.values, 
  minbucket.values = minbucket.values, 
  m = 2
)$Syn

k.decision <- function(synt.data, k.real){
  m <- length(synt.data)
  k.synt <- numeric(m)       # vector to store the optimal k values
  ssynt.data <- list(m)      # scaled synthetic datasets
  clust.synt <- list(m)      # clustering results

  for (i in 1:m){
    kopt.synt <- NbClust(data = synt.data[[i]], diss = NULL, distance = "euclidean", method = "kmeans", index = "all", alphaBeale = 0.1)
    k.synt[i] <- as.numeric(names(table(as.vector(kopt.synt$Best.nc[1,])))[which.max(table(as.vector(kopt.synt$Best.nc[1,])))])

    ssynt.data[[i]] <- scale(synt.data[[i]])
    clust.synt[[i]] <- kmeans(ssynt.data[[i]], k.synt[i], nstart = 25)  # clustering result
  }

  clustering.result <- list("K optim" = k.synt, "Clustering" = clust.synt)
  i <- which(k$`K optim` == kreal)  # select those with same number of clusters as in real data
  clustering.result <- lapply(clustering.result, `[`, i)
  return(clustering.result)
}

clustering.result <- k.decision(synt.data = synt.data)

# Keep only those that have the same number of clusters as the real data
i <- which(k$`K optim` == 2)        # replace 2 with the optimal k of real data
clustering.result <- lapply(clustering.result, `[`, i)
```

# K desicion's function V2
```{r}
k.decision <- function(data, k.real = 0, synthetic = TRUE){
  if(synthetic == TRUE){
    kopt.obj <- NbClust(data = data, diss = NULL, distance = "euclidean", method = "kmeans", index = "all", alphaBeale = 0.1)
    kopt <- as.numeric(names(table(as.vector(kopt.obj$Best.nc[1,])))[which.max(table(as.vector(kopt.obj$Best.nc[1,])))])
    
    if(kopt == k.real){
      sdata <- scale(data)
      clust <- kmeans(sdata, kopt, nstart = 25)
      
      clustering.result <- list("K optim" = kopt, "Clustering" = clust)
      return(clustering.result)
    }
  } else {
    kopt.obj <- NbClust(data = data, diss = NULL, distance = "euclidean", method = "kmeans", index = "all", alphaBeale = 0.1)
    kopt <- as.numeric(names(table(as.vector(kopt.obj$Best.nc[1,])))[which.max(table(as.vector(kopt.obj$Best.nc[1,])))])
    sdata <- scale(data)
    clust <- kmeans(sdata, kopt, nstart = 25)
    
    clustering.result <- list("K optim" = kopt, "Clustering" = clust)
    return(clustering.result)
  }
}

k.real <- k.decision(real.data.1, synthetic = FALSE)$`K optim`
km.real <- k.decision(real.data.1, synthetic = FALSE)$Clustering

result <- lapply(synt.data, k.decision, k.real = k.real, synthetic = TRUE)
k.synt <- as.vector(lapply(result, function(res) res[["K optim"]]))
km.synt <- lapply(result, function(res) res[["Clustering"]])
```


# Label switching
```{r}
library(clue)

label.switching <- function(km.real, km.synt){
  if(!is.null(km.synt)){
      centroids <- rbind(km.real$centers, km.synt$centers)
      dist.global <- as.matrix(dist(centroids, method = "euclidean"))
      n.real <- nrow(km.real$centers) #number of cluster in real dataset
      n.synt <- nrow(km.synt$centers) #number of cluster in synthetic dataser
      dist <- dist.global[1:n.real, (n.real + 1) : (n.real + n.synt)]
      label.ass <- solve_LSAP(dist, maximum = FALSE) 
      
      # Synthetic data relabeling
      km.synt$recluster <- km.real$cluster # new variable
      
      for (i in 1:length(label.ass)) {
        km.synt$recluster[km.synt$cluster == label.ass[i]] <- i
      }
  }
  return(km.synt)
}

label.switching.test <- label.switching(km.real=km.real, km.synt=km.synt[[2]])
label.switching.test$cluster
label.switching.test$recluster
fviz_cluster(km.real, data = scale(real.data.1),
             palette = colours[1:k.real],
             ellipse.type = "euclid", 
             star.plot = TRUE, 
             repel = TRUE,
             ggtheme = theme_minimal())

fviz_cluster(km.synt[[2]], data = scale(synt.data[[2]]),
             palette = colours[1:k.real],
             ellipse.type = "euclid",
             star.plot = TRUE, 
             repel = TRUE,
             ggtheme = theme_minimal())

ls.km.synt <- lapply(km.synt, function(ls) label.switching(km.real, ls))
```